### ISSUE TITLE
Maintenance?

### ISSUE THREAD

**Issue by gforcada** [collective/ploneconf-gatsby#59]
Seems that dependabot is quite keen on creating new PRs for this project, but without anyone merge and managing the project, it feels rather useless.

@Arhell is keen on reviewing them, which is appreciated, but if no action is taken afterwards, seems again a waist of time.

@Arhell do you happen to have any special interest in this package and might want to jump to maintain it? 😄 🍀

**Comment by Arhell** [comment]
I can support this project, but where is it used and what is it mainly for?

**Comment by gforcada** [comment]
Are you using it yourself? Are you planning to use it at any near future? Otherwise there is not really much interest in spending time maintaining something that nobody uses 😅 

`collective` is an organization umbrella for Plone related add-ons to be maintained collectively by Plone developers. It makes it easier to collaborate by having a shared organization.

At the same time though, it is easy to leave projects unmaintained as they might no longer serve any purpose, a new add-on is more useful, code got integrated into plone core, etc etc

Doing any maintenance effort on a project that has no real users, does not make sense, at least to me, and only adds noise.

**Comment by Arhell** [comment]
I understood, then no, because I don’t use it, I heard you, I will look at projects that are used and not old ones, thanks.
